---

#install files for webserver
- hosts: localhost

  tasks:
  - name: Install latest version of apache, mysql, php, and php support for mysql and apache
    yum:
        name: apache2, mysql-server, php, libapache2-mod-php, php-mcrypt, php-mysql
        state: latest
  

        